### ISSUE TITLE
`properties` property

### ISSUE THREAD

**Issue by kiwiz** [owenrumney/go-sarif#13]
According to the [spec](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317449):
> In addition to those properties that are explicitly documented, every object defined in this document MAY contain a property named properties whose value is a property bag. This allows SARIF producers to include information about each object that is not explicitly specified in the SARIF format.

This sounds a bit hairy to implement - would every object have a `PropertyBag` object? How would the interface to that look? For my usecase, I'm looking to set `properties` on `run`, `toolComponent` and `result` but I thought it'd be worthwhile to discuss this in general.

Also, gratz on v1.0.0!

**Comment by owenrumney** [comment]
Hey @kiwiz  - yup, been reading up on this. got the basis of an idea so will push soon!

**Comment by owenrumney** [comment]
Hey, @kiwiz  - what do you think about something like this

```
func (r *runTest) properties_added_to_a_run() {
	pb := r.run.GetPropertyBag()
	pb.AddString("string_key", "string_value")
	pb.AddBoolean("boolean_key", false)
}
```
which gives the output
```json
{
   "tool":{
      "driver":null
   },
   "properties":{
      "boolean_key":false,
      "string_key":"string_value"
   }
}
```

Thoughts?

**Comment by kiwiz** [comment]
Looks reasonable - the interface matches the rest of the library. Having to explicitly pull out the `PropertyBag` is an extra step, but the speedbump might encourage tool writers to look for a native SARIF field that does what they want.

**Comment by owenrumney** [comment]
The alternative, which probably is more sensible and the same result means the same `PropertyBag` can be added to multiple blocks. I think this might be the better way
```golang
func (r *runTest) properties_added_to_a_run() {
	pb := sarif.NewPropertyBag()

	pb.AddString("string_key", "string_value")
	pb.AddBoolean("boolean_key", false)
	
	r.run.AttachPropertyBag(pb)
}
```
