### ISSUE TITLE
Suggestion to change Rule Properties type definition

### ISSUE THREAD

**Issue by zendern** [owenrumney/go-sarif#18]
I'm attempting to use this library to build out a code scan in github. Based on this definition 

https://docs.github.com/en/code-security/secure-coding/integrating-with-code-scanning/sarif-support-for-code-scanning#reportingdescriptor-object

ReportingDescriptor in github == Rule here. 

I believe that we should change Properties from a `map[string]string` to simply `Properities` 

https://github.com/owenrumney/go-sarif/blob/73511fbe9a4ff2dde7a51d8e25985ad9a331fb57/sarif/tool.go#L31

Which would match what Run has setup today. 

https://github.com/owenrumney/go-sarif/blob/73511fbe9a4ff2dde7a51d8e25985ad9a331fb57/sarif/run.go#L20

Also would be nice to have a corresponding `AttachPropertyBag` method on this struct like we do here on Run. 

https://github.com/owenrumney/go-sarif/blob/73511fbe9a4ff2dde7a51d8e25985ad9a331fb57/sarif/run.go#L75-L77

Let me know your thoughts. I'm happy to PR that change in.

**Comment by owenrumney** [comment]
Hey @zendern  - thanks for this - I've done it as a quick fix for now. I need to spend some time working out how ReportingDescriptor/Rule/Notification all intertwine and handle deprecated Ids as per the Sarif spec

Also, my documentation is lacking, now that I know there are a few people using  (or trying to use) this I'll tidy that too!

**Comment by zendern** [comment]
@owenrumney awesome thank you. 🥇 🥇 I'll give it a go later today but those changes look to be what I would need.
