### ISSUE TITLE
Support for `originalUriBaseIds` field

### ISSUE THREAD

**Issue by dev-gaur** [owenrumney/go-sarif#22]
We have a field for UriBaseId , but we don't have any option to specify the list of originalUriBaseIds .

https://github.com/microsoft/sarif-tutorials/blob/main/samples/OriginalUriBaseIds.sarif#L15

Correct me if I'm wrong.

**Comment by owenrumney** [comment]
Hey @dev-gaur  - I only implemented enough to get it working for us.

I've since done all the other properties under v2 which I'll release shortly.

It's entirely possible you've found an alternative solution because I took so long - apologies if this is the case!
