### ISSUE TITLE
Update Sarif Schema

### ISSUE THREAD

**Issue by shaopeng-gh** [owenrumney/go-sarif#26]
Hello! this is Shaopeng from Microsoft Sarif team. Our team creates and maintains the Sarif format standard.
https://github.com/oasis-tcs/sarif-spec
https://github.com/microsoft/sarif-sdk
https://github.com/microsoft/sarif-js-sdk
https://github.com/microsoft/sarif-website

Glad to see ‎go-sarif supports Sarif format for Go Language!

Question, can we update to the latest Sarif schema, (no breaking changes)

I have created a PR just for find and replace:
https://github.com/owenrumney/go-sarif/pull/25

Thank you,

**Comment by owenrumney** [comment]
Thanks @shaopeng-gh  - I need to get back to checking that the whole spec is fully supported - I've neglected it a little.

Thanks again for your input, great to know the maintainers of Sarif format standard know this project exists.
