### ISSUE TITLE
broken package

### ISSUE THREAD

**Issue by figadore** [owenrumney/go-sarif#28]
isn't 1.0.13 technically a breaking change?

```
go get: github.com/owenrumney/go-sarif@v1.0.12 updating to
	github.com/owenrumney/go-sarif@v1.0.13: parsing go.mod:
	module declares its path as: github.com/owenrum/go-sarif
	        but was required as: github.com/owenrumney/go-sarif
```

**Comment by owenrumney** [comment]
Yes - it was a very regretable disaster - I should never have tried to rename my account

v1.0.14 should get things back on track and we can pretend this never happened :grimacing: 

(genuine apologies for the inconvenience)
