### ISSUE TITLE
Add recommended `help.markdown` field for rules

### ISSUE THREAD

**Issue by afdesk** [owenrumney/go-sarif#29]
@owenrumney thanks for your project!

Now, I'm trying to migrate `trivy` sarif template from Go Template to Go code.

I'd like to have `help.markdown` field for the rule. this is recommended on Github: [reportingDescriptor objects that represent rules](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#reportingdescriptor-object).

What is the best way to add it?

thanks for your help!

**Comment by owenrumney** [comment]
Hey @afdesk - This was already there but there didn't seem to be a helper method for it. I've noticed that a lot of my naming is off too so that has been updated.

if you can switch to `github.com/owenrumney/go-sarif/v2` that would be a plus too

```go
run.AddRule(r.RuleID).
	WithDescription(r.Description).
	WithHelp(r.Link).
	WithProperties(pb.Properties).
	WithMarkdownHelp("# markdown")
```

**Comment by afdesk** [comment]
Hi @owenrumney! 
can you help me again?
It seems that there is a problem with `help.markdown`.
There is no way to use the both fields: `text` and `markdown`.
thanks a lot!
https://github.com/owenrumney/go-sarif/blob/8a2f9b473a872089bd8227313c457ea72c53de24/sarif/reporting_descriptor.go#L66-L76

**Comment by afdesk** [comment]
@owenrumney I've added a PR for your review. maybe it'll be useful.
