### ISSUE TITLE
Support `ruleIndex` field for the results

### ISSUE THREAD

**Issue by afdesk** [owenrumney/go-sarif#33]
Hi @owenrumney!

Tell me, please, Are there any plans to support `ruleIndex` field for the result items?
result-object: [result-object](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#result-object)

thanks!

**Comment by owenrumney** [comment]
Hey @afdesk  - v2 is about to support EVERYTHING, including `ruleIndex` for Result - https://github.com/owenrumney/go-sarif/blob/cf6ff34b81dcccce63b5c232469f168031d5b27f/v2/sarif/result.go#L9

I'm having to do it as v2 because there are breaking changes - I think its going to be worth the pain though.  I'll release today

**Comment by owenrumney** [comment]
@afdesk  - I've released v2.0.10 - seems to download okay with `go get github.com/owenrumney/go-sarif/v2`

**Comment by afdesk** [comment]
@owenrumney thanks a lot!
I'll try to update my code today or tomorrow.

**Comment by afdesk** [comment]
@owenrumney yes, I can use v2 now.

tell me, please, is there a way to use `ruleIndex`?
I mean that I'd like to get the index of the associated rule here:
https://github.com/owenrumney/go-sarif/blob/cf6ff34b81dcccce63b5c232469f168031d5b27f/v2/sarif/reporting_descriptor.go#L4-L14

thanks a lot!

**Comment by owenrumney** [comment]
Hey @afdesk  - I've updated to v2.0.12

Now when you create a result it will set the rule index for you. Try running the code in example to see.

The condition is that you MUST add the rule before you add the result so that it can be looked up.

**Comment by owenrumney** [comment]
Closing as this should be resolved. Please feel free to reopen if not
