### ISSUE TITLE
sarif report without results

### ISSUE THREAD

**Issue by afdesk** [owenrumney/go-sarif#36]
Hi @owenrumney!
It seems that I already bore you, sorry!

githbub can't accept a report without vulnerabilities / misconfigurations, because:
```json
"results": null
```
should `trivy` handle this case itself?
thanks a lot again!

**Comment by owenrumney** [comment]
Hey @afdesk  - no problem at all - I'm grateful to you for helping to shake out the issues

I"m guessing you're doing

```go
run := sarif.NewRun(tool)
```

rather than 

```go
run := sarif.NewRunWithInformationURI("trivy", "https://aquasecurity.github.io/trivy")
```

which is fine - there was a bug in `NewRun` which is fixed in `v2.0.13` - please try that and let me know if there is still an issue

**Comment by afdesk** [comment]
> I"m guessing you're doing
> 
> ```go
> run := sarif.NewRun(tool)
> ```
> 
> rather than
> 
> ```go
> run := sarif.NewRunWithInformationURI("trivy", "https://aquasecurity.github.io/trivy")
> ```

oh, thanks!
yes, i did so, because I want to set a version via `tool`.
now, I'm doing:
```go
sw.run = sarif.NewRunWithInformationURI("Trivy", "https://github.com/aquasecurity/trivy")
sw.run.Tool.Driver.WithVersion(sw.Version)
```

**Comment by afdesk** [comment]
@owenrumney sorry, I have a problem again. 
`ToolComponent.Rules` is `nil` for report without results.
could you fix it, please? thanks a lot!

**Comment by owenrumney** [comment]
Hey @afdesk  - take v2.0.16 and it has the default empty rules rather than null

**Comment by afdesk** [comment]
thanks a lot, will try a new version!
