### ISSUE TITLE
`fullName` for ToolComponent

### ISSUE THREAD

**Issue by afdesk** [owenrumney/go-sarif#37]
The current version of sarif template for `trivy` contains field `fullName`. but i can't find information about it.
maybe it's already deprecated.

@owenrumney what do you think about it?

**Comment by owenrumney** [comment]
@afdesk  - I've added all the missing helpers for `ToolComponent` to `v2.0.15` 

Again, sorry you're having to find these issues for me to resolve, think we're pretty much there now though
