### ISSUE TITLE
Update sarif schema

### ISSUE THREAD

**Issue by DmitriyLewen** [owenrumney/go-sarif#58]
Hello!

https://sarifweb.azurewebsites.net/Validation says that `sarif-2.1.0-rtm.5.json` is not final version.
```
[SARIF1011](http://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html): $schema: The '$schema' property value 'https://json.schemastore.org/sarif-2.1.0-rtm.5.json' does not refer to the final version of the SARIF 2.1.0 schema. If you are using an earlier version of the SARIF format, consider upgrading your analysis tool to produce the final version. If this file does in fact conform to the final version of the schema, upgrade the tool to populate the '$schema' property with a URL that refers to the final version of the schema.
```

Looks like `sarif-2.1.0-rtm.5.json` > `sarif-2.1.0.json` and [sarif-2.1.0.rtm-6.json](https://json.schemastore.org/sarif-2.1.0-rtm.6.json) doesn't exist.

Can you help me understand what I am missing?

Best Regards, Dmitriy!

**Comment by owenrumney** [comment]
Hey @DmitriyLewen - I've added a `sarif.Version210RTM5` which points to `sarif-2.1.0-rtm.5.json` and redirected `sarif.Version210` to `sarif-2.1.0.json`.

All that should be required is to update to `v2.2.0` of `go-sarif` and the change should validate

**Comment by DmitriyLewen** [comment]
Hello @owenrumney 
Cool! Thanks a lot!
