### ISSUE TITLE
Add the deprecatedIds field in rule

### ISSUE THREAD

**Issue by another-rex** [owenrumney/go-sarif#66]
Can you add the `3.49.4 deprecatedIds` property to rules? Currently I am putting it in `properties` field, but since it's an official field it should not be in a field under properties. Thanks!

**Comment by owenrumney** [comment]
Thanks for the issue, this is resolved in v2.2.1

**Comment by owenrumney** [comment]
@another-rex - Just spotted this library is being used in osv-scanner.

Please shout if there is anything else that feels deficient and I'll get on it promptly
